### ISSUE TITLE
format of config/dataset/dataset.yaml

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#81]
What is the rationale behind the "dict of list of singleton dicts of list of singleton dicts" structure in `dataset.yaml`, instead of dict of dicts of dicts? Why not use

```
time_manipulation: dataset/time_manipulation
unchecked_ll_calls: dataset/unchecked_low_level_calls
solidiFI: 
    url: https://github.com/smartbugs/SolidiFI-benchmark.git
    local_dir: dataset/solidiFI
    subsets: # Accessed as solidiFI/name 
        overflow_underflow: buggy_contracts/Overflow-Underflow
        reentrancy: buggy_contracts/Re-entrancy
        tod: buggy_contracts/TOD
```

instead of

```
time_manipulation: dataset/time_manipulation
unchecked_ll_calls: dataset/unchecked_low_level_calls
solidiFI: 
   -  url: https://github.com/smartbugs/SolidiFI-benchmark.git
    - local_dir: dataset/solidiFI
    - subsets: # Accessed as solidiFI/name 
        - overflow_underflow: buggy_contracts/Overflow-Underflow
        - reentrancy: buggy_contracts/Re-entrancy
        - tod: buggy_contracts/TOD
```

Would make the code processing it simpler ...
